version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chiliz-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chiliz
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
